config/routes.rb
Et::Application.routes.draw do

  resources :users do
    resources :comments
  end
  resources :sessions, only:[:new,:create,:destroy]
  
  resources :teachers do
    resources :comments
  end
  match '/signup', to:'users#new'
  
  match '/signin', to:'sessions#new'
  match '/signout', to:'sessions#destroy'

  get 'comments/create'

  root :to => 'home#index'

end

app/models/college.rb
class College < ActiveRecord::Base
  attr_accessible :name

  validates :name, presence:true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :teacher_id, :o, :s

  belongs_to :teacher
  belongs_to :user 

  validates :content, presence:true
  validates :teacher_id, presence:true
  validates :user_id, presence:true

  default_scope order:'Comments.created_at DESC'

  def getUser
  	User.find(self.user_id)
  end

   def getTeacher
  	Teacher.find(self.teacher_id)
  end
end

app/models/drop_remove_o_froms.rb
class DropRemoveOFroms < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/remove_o_from.rb
class RemoveOFrom < ActiveRecord::Base
  attr_accessible :comments
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  attr_accessible :college, :name

  has_many :comments,dependent: :destroy
  validates :name, presence:true

  	def getCollege
		College.find_by_id(self.college).name
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  has_many :comments,dependent: :destroy
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment=current_user.comments.build( {content:params[:comment][:content],teacher_id:params[:teacher_id] })
		if @comment.save
			flash[:success] = "Comment Success"
		else
			flash[:error] = "Post failed !"
		end
		redirect_to controller:'teachers', action:'show', id:params[:teacher_id]
	end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if !signed_in?
  		redirect_to '/signin'
  	end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		 user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error]= 'Invalid email/password combination' 
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to '/signin'
	end
end

app/controllers/teachers_controller.rb
#encoding:UTF-8
class TeachersController < ApplicationController
	
	def new
	end

	def index
    	@teachers=Teacher.paginate({ page:params[:page],per_page:10 })		
	end

	def create
		@teacher=Teacher.new(name:params[:name],college:params[:college])
		if @teacher.save
      		flash[:success]="创建教师成功！"
			redirect_to @teacher
		else
			flash.now[:error]="Create failed,try again！"
			render 'new'
		end
	end

	def show
		@teacher=Teacher.find(params[:id])
		@comments=@teacher.comments.paginate(page:params[:page])
		@new_comment=@teacher.comments.build
	end


	
end

app/controllers/users_controller.rb
#encoding:UTF-8
class UsersController < ApplicationController
  
  before_filter :signed_in_user,only:[:edit,:update,:index]
  before_filter :correct_user,only:[:edit,:update]

  def new
  	@user=User.new
  end

  def create
  	@user=User.new(params[:user])
  	if @user.save
      sign_in @user
      flash[:success]="欢迎来到教师点评网"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
      @user=User.find(params[:id])
      @dynamic_comments=@user.comments.paginate(page:params[:page])
  end

  def edit
      @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = 'Profile updated'
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users=User.paginate({ page:params[:page],per_page:10 })
  end

  private
    def signed_in_user
      redirect_to signin_url,notice:"Please login first" unless signed_in?
    end

    def correct_user
      @user=User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
# encoding: utf-8
module ApplicationHelper
	def full_title(page_title)
		base_title = '教师点评网'
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def current_user?(user)
		current_user==user
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		self.current_user=nil
		cookies.delete(:remember_token)
	end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<li>
  <div class="row">
  	<div class="span1">
  		<a href="#" title="赞成" class="tooltip-support"><i class="icon-thumbs-up icon-large"></i></a>
  		<br />
  		<a href="#" title="反对" class="tooltip-oppose"><i class="icon-thumbs-down"></i></a>
  	</div>
  	<div class="span7">
  	    <span class="user-comment">
	  		<a href="<%= url_for controller:'users', action:'show', id:comment.user.id %>"><%= comment.user.name%></a>
	  	</span>
	  	<span class="timestamp-comment">
	    	Posted <%= time_ago_in_words(comment.created_at) %> ago.
	  	</span>
	  	<br />
		<span class="content-comment"><pre><%= comment.content %></pre></span>
  	</div>
  <div>
</li>

app/views/home/index.html.erb
<% provide(:title,'评价老师,让课堂变得更有效率...') %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyrights @ <%= link_to '教师点评网',root_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "教师点评网", root_path, id: "logo" %>
      <nav>

        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Teachers",    teachers_path %></li>
            <li><%= link_to "Users", users_path %></li>
            
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>

          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>

          <!-- Button to trigger modal AddTeacher-->
        <% if signed_in? %>
          <a href="#AddTeacher" class="btn btn-small btn-inverse pull-right" data-toggle="modal">添加</a>

          <form class="navbar-search pull-right">
            <input type="text" class="search-query" placeholder="找老师...">
          </form>
        <% end %>

      </nav>
    </div>
  </div>
</header>

<%= render 'teachers/new' %>

app/views/layouts/_shim.html.erb
 <!-- [if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
 <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if !Rails.env.development? %>
    </div>
</body>
</html>

app/views/share/_comment_form.html.erb
<%= form_for([@teacher,@new_comment]) do |f| %>
	<%= f.text_area :content,rows:4 %>

	<%=f.submit "加上去", class:"btn btn-mini"%>
<% end %>

app/views/share/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%=pluralize(@user.errors.count,"error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li>* <%=msg %></li>
			<%end%>
		</ul>
	</div>
<%end%>

app/views/teachers/_new.html.erb
<!-- Modal -->
<div class="modal hide fade" id="AddTeacher">
            
  <div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h3>添加教师</h3>
  </div>
  <%= form_tag({:controller => "teachers", :action => "create"}, :method => "post") do %>            
  <div class="modal-body">
    <%= label_tag(:name, "Name:") %>
    <%= text_field_tag(:name) %>

    <%= label_tag(:college, "College:") %>
    <% college_array = College.all.map { |college| [college.name, college.id] }%>
    <%= select_tag(:college, options_for_select(college_array)) %>
    
  </div>
            
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal">取消</button>
    <button class="btn btn-primary">添加</button>
  </div>
  <% end %>
</div>

app/views/teachers/index.html.erb
<% provide(:title, 'Teachers') %>
<h1>All Teachers</h1>

<ul class="teachers">
  <% @teachers.each do |teacher| %>
    <li>
      <%= link_to teacher.name, teacher %>&nbsp;&nbsp;<small><%= teacher.getCollege%></small>
    </li>
  <% end %>
</ul>

<%=will_paginate %>

app/views/teachers/new.html.erb
<% provide(:title,'添加教师') %>
<h1>添加教师</h1>
<%= form_tag({:controller => "teachers", :action => "create"}, :method => "post") do %>
	<%= label_tag(:name, "Name:") %>
	<%= text_field_tag(:name) %>

    <%= label_tag(:college, "College:") %>
    <% college_array = College.all.map { |college| [college.name, college.id] }%>
    <%= select_tag(:college, options_for_select(college_array)) %>
	<button class="btn btn-primary">添加</button>
<% end %>

app/views/teachers/show.html.erb
<%= provide(:title,@teacher.name) %>
<ul class="thumbnails">
	<li class="span12"><h3><%= @teacher.name %></h3></li>
	<li class="span8 detail"><%= College.find(@teacher.college).name %></li>
	<li class="span8">
			<% if @teacher.comments.count != 0 %>
				<h4 class="teacher-comment-dynamic">总共有<%= @teacher.comments.count %>条评价：</h4>
				<ul class="comments">
					<%= render @comments %>
				</ul>
				<%= will_paginate @comments %>
			<% else%>
				<h4 class="teacher-comment-dynamic">
					该老师暂无评价,<a href="#" onclick="document.getElementById('comment_content').focus();">添加</a>
				</h4>
			<% end -%> 
	</li>

	<li class="span12"><hr/></li>
	<li class="span8"><h4 class="teacher-comment-dynamic">评价该老师：</h4></li>
	<li class="span8"><%= render 'share/comment_form' %></li>
</ul>


 

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render "share/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>All Users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%=will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render "share/error_messages" %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name)%>
<ul class="thumbnails">
	<li class="span12"><h3><%= @user.name %></h3></li>
	<li class="span8 detail">邮箱: <%= @user.email %></li>
	<li class="span8">

			<% if @user.comments.count!=0 %>
				<h4 class="user-dynamic-title">最近动态：</h4>
				<ul class="user-dynamic-details">
					<% @dynamic_comments.each do |c| %>
						<li>
						  <span class="timestamp-dynamic"><%= time_ago_in_words(c.created_at) %> ago,commented <a href="<%= url_for controller:'teachers', action:'show', id:c.getTeacher.id %>"><%= c.getTeacher.name%></a></span>
						  <br /><br />
						  <span class="content-dynamic">
						  	<%= c.content %>
						  </span>
						</li>
					<% end %>
				</ul>
			<% else%>
				<h4 class="user-dynamic-title">
					暂无动态
				</h4>
			<% end -%> 
	</li>

</ul>